name: Rebekah Build Validation

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y build-essential
        fi
      shell: bash

    - name: Compile
      run: gcc src/Rebekah.c src/Lexer/Lexer.c src/Parser/Parser.c src/Compiler/Semantics.c src/Compiler/IR.c src/Compiler/Codegen/IRGen.c src/Compiler/Optimization/IROptimization.c src/VirtualMachine/VirtualMachine.c -o Rebekah
        
    - name: Run Tests
      run: ./Rebekah --run-tests
